apiVersion: v1
kind: Secret
metadata:
  name: application-secret
data:
  DB_USERNAME: "cG9zdGdyZXM="
  DB_PASSWORD: "MTIzNDU2Nzg="
  DB_URL: "amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL3VzZXJkYg=="