apiVersion: v1
kind: Service
metadata:
  name: sample-kubernetes-application-service
spec:
  selector:
    tier: backend
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30009